development:
  adapter: postgresql
  encoding: unicode
  database: danalex93_development
  pool: 5
  username: danalex93
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: danalex93_test
  pool: 5
  username: danalex93
  password:
production:
  adapter: danalex93
  encoding: unicode
  database: danalex93_production
  pool: 5
  username: danalex93
  password: